# Add full projects here as you build them
# add_subdirectory(chip8_emulator)
# add_subdirectory(raytracer)

add_executable(
        compound_interest_calculator
        compound_interest_calculator/compound_interest_calculator.cpp
)

add_executable(
        simple_interest_calculator
        simple_interest_calculator/simple_interest_calculator.cpp
)

add_executable(
        unit_converter
        unit_converter/unit_converter.cpp
)