name: Cppcheck Static Analysis

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cppcheck-scan:
    name: Run Cppcheck Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run Cppcheck
        run: |
          echo "=================== STARTING CPPCHECK ==================="
          cppcheck \
            --enable=warning,style,performance \
            --inline-suppr \
            --std=c++20 \
            --language=c++ \
            --suppress=missingIncludeSystem \
            --suppress=unmatchedSuppression \
            compiled-projects/
          echo "=================== CPPCHECK COMPLETE ==================="